version: '3.8'

services:
  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/backoffice-veiculos
      - JWT_SECRET=your-super-secret-jwt-key-here
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=backoffice-veiculos
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
